# Generated by Django 5.1.1 on 2024-10-23 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_fotografia_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='data',
            new_name='data_fotografia',
        ),
    ]
